### ISSUE TITLE
La criticidad del inspector va asignada a la opcion de respuesta, no a la pregunta

### ISSUE THREAD

**Issue by victorcatn** [gomac-un/app_inspecciones#19]
En las respuestas de seleccion unica, se debe mostrar el slider de criticidad del inspector solo si la opcion de respuesta puede ser "calificable".
En las de seleccion numérica se puede "calificar" la respuesta, que sería el número.
Para las de selección múltiple necesito que @jcorreapa me lo aclare porque podríamos tener varias opciones calificables en una sola pregunta.

Sería bueno reconsiderar esto y dejar la "calificacion" para la pregunta, eso simplifica mucho las cosas y sigue siendo útil.

**Comment by jcorreapa** [comment]
Hay algunas opciones que no requieren que se les califique, por ejemplo, si la opción es 'Falta' ya tiene asignada una criticidad desde la creación y no sería necesario que el inspector asigne una criticidad propia. Pero si la opción es digamos 'Fisuras' tal vez el inspector si pueda agregar criticidad para indicar la gravedad de la figura.

Entonces se tendría que poner la criticidad del inspector en la parte de los detalles, cuando esté seleccionada la opción.

**Comment by victorcatn** [comment]
Al final se dejó el mismo comportamiento que tenia la app v1
